version: "3.7"

x-logging: &logging
  logging:
    driver: "json-file"
    options:
      max-file: "5"
      max-size: "10m"

x-restart-policy:
  restart: unless-stopped

services:
  postgres:
    <<: *logging

    image: "docker.io/postgres:15-alpine"

    ports:
      - "5432:5432"

    environment:
      POSTGRES_DB: xythrion
      POSTGRES_PASSWORD: xythrion
      POSTGRES_USER: xythrion

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U xythrion"]
      interval: 2s
      timeout: 1s
      retries: 5

  api:
    <<: *logging

    build:
      context: ./api
      dockerfile: Dockerfile

    env_file:
      - .env

    environment:
      DATABASE_URL: postgresql://xythrion:xythrion@postgres:5432/xythrion

    volumes:
      - ./api:/api

    depends_on:
      - postgres

    ports:
      - "8001:8000"

  prometheus:
    <<: *logging

    container_name: prometheus

    image: "docker.io/prom/prometheus"

    volumes:
      - ./services/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

    ports:
      - "9090:9090"
