name: CI

on:
  push:
    branches:
    - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  api-ci:
    name: API CI

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        directory: ["api"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        cache: "pip"
        cache-dependency-path: "${{ matrix.directory }}/pyproject.toml"

    - name: Set up PDM
      uses: pdm-project/setup-pdm@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      working-directory: ${{ matrix.directory }}
      run: pdm sync

    - name: Run lints
      working-directory: ${{ matrix.directory }}
      run: pdm lint

    - name: Run tests with coverage
      working-directory: ${{ matrix.directory }}
      run: pdm test-cov

  site-ci:
    name: Site CI

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        directory: ["site"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - uses: oven-sh/setup-bun@v1
      with:
        bun-version: "latest"

    - name: Install dependencies
      working-directory: ${{ matrix.directory }}
      run: bun install

    - name: Run linting
      working-directory: ${{ matrix.directory }}
      run: bun ci
